<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.LocalStorage" Version="10.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="7.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" Version="9.8.0" />
    <PackageReference Include="SqliteWasmBlazor" Version="0.9.1-pre" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <Target Name="BundleJS" BeforeTargets="BeforeBuild">
    <Exec Command="npm run build:ts:$(Configuration.ToLower())" />
  </Target>

  <ItemGroup>
    <Content Remove="tsconfig.json" />
    <None Include="tsconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../EnglishLeitner.EFDesign/EnglishLeitner.EFDesign.csproj" />
  </ItemGroup>

</Project>
