name: CD

on:
  push:
    branches:
      - main
    paths:
      - '*.slnx'
      - '.github/workflows/cd.yml'
      - 'src/EnglishLeitner.WebClient/**'
permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      PROJECT_PATH: "./src/EnglishLeitner.WebClient"

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cache NuGet packages
        uses: actions/cache@v6
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln', '**/Directory.Packages.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
          dotnet-quality: 'ga'
          cache: true
          cache-dependency-path: |
            **/*.slnx
            **/Directory.Packages.props
            ${{ env.PROJECT_PATH }}/**/*.csproj

      - name: Install .NET wasm-tools workload
        run: dotnet workload install wasm-tools

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: ${{ env.PROJECT_PATH }}/package-lock.json

      - name: Cache npm packages
        uses: actions/cache@v6
        with:
          path: ${{ github.workspace }}/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install npm dependencies
        run: npm i --save
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Download Database from GitHub Releases
        run: |
          mkdir -p data
          curl -L -o data/app.db "https://github.com/alireza-rezaee/english-leitner/releases/download/0.9.0-alpha.1/app.db"
        working-directory: ${{ env.PROJECT_PATH }}/wwwroot

      - name: Publish .NET Project
        run: dotnet publish EnglishLeitner.WebClient.csproj -c Release -o release --nologo
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Add error.html file
        run: cp index.html error.html
        working-directory: ${{ env.PROJECT_PATH }}/release/wwwroot

      - name: Upload to ArvanCloud Object Storage
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.ARVAN_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARVAN_SECRET_KEY }}
          ARVAN_BUCKET: ${{ secrets.ARVAN_BUCKET }}
          AWS_DEFAULT_REGION: default
        run: |
          aws s3 sync ${{ env.PROJECT_PATH }}/release/wwwroot s3://${{ env.ARVAN_BUCKET }} \
            --endpoint-url "https://s3.ir-thr-at1.arvanstorage.ir" \
            --delete \
            --exact-timestamps
