// <auto-generated />
using System;
using EnglishLeitner.EFDesign.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishLeitner.EFDesign.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818074240_AddReviews")]
    partial class AddReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MeaningItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeaningItemId");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.MeaningGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Head")
                        .HasColumnType("TEXT");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("MeaningGroups");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.MeaningItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cefr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Definition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grammar")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeaningGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Refs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variants")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeaningGroupId");

                    b.ToTable("MeaningItems");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.Pronunciation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Culture")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mp3Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("OggUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonetics")
                        .HasColumnType("TEXT");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("Pronunciations");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemembered")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cefr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grammar")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadWord")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeitnerLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextTryUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebPage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.Example", b =>
                {
                    b.HasOne("EnglishLeitner.EFDesign.Models.MeaningItem", "MeaningItem")
                        .WithMany("Examples")
                        .HasForeignKey("MeaningItemId");

                    b.Navigation("MeaningItem");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.MeaningGroup", b =>
                {
                    b.HasOne("EnglishLeitner.EFDesign.Models.Word", "Word")
                        .WithMany("Meanings")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.MeaningItem", b =>
                {
                    b.HasOne("EnglishLeitner.EFDesign.Models.MeaningGroup", "MeaningGroup")
                        .WithMany("Meanings")
                        .HasForeignKey("MeaningGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeaningGroup");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.Pronunciation", b =>
                {
                    b.HasOne("EnglishLeitner.EFDesign.Models.Word", "Word")
                        .WithMany("Pronunciations")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.Review", b =>
                {
                    b.HasOne("EnglishLeitner.EFDesign.Models.Word", "Word")
                        .WithMany("Reviews")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.MeaningGroup", b =>
                {
                    b.Navigation("Meanings");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.MeaningItem", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("EnglishLeitner.EFDesign.Models.Word", b =>
                {
                    b.Navigation("Meanings");

                    b.Navigation("Pronunciations");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
